### PR TITLE
Ch basic app structure

### LINKED ISSUE #2: setup flask project
Set up the basic flask project structure

### PR DESCRIPTION
**Pull request by mariamiah**
## Description
- set up the basic flask app structure

Fixes #2 

## How Has This Been Tested?
- set up a virtual environment by running `python3 -m venv venv`
- activated the virtualenvironment using `source venv/bin/activate`
- installed Flask `pip install Flask`
- setup a test endpoint at the home route
- ran the app using `python run.py`

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have added necessary inline code documentation
- [ ] I have added tests that prove my fix is effective and that this feature works
- [ ] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Review by skizza8 — APPROVED** [review]
Initial Setup looks good

**Comment by daisymacharia** [comment]
Setup looks good

**Review by daisymacharia — APPROVED** [review]
Setup looks good

**Comment by AineKiraboMbabazi** [comment]
This structure looks okay.

**Review by daisymacharia — APPROVED** [review]

**Review by skizza8 — APPROVED** [review]

**Review by AineKiraboMbabazi — APPROVED** [review]

**Pull request merged**
